-- Jalankan sekali melalui Supabase SQL Editor untuk fitur login dan aktivitas admin.
-- Jangan pernah memasukkan secret/service_role key ke aplikasi Vite/browser.

create table if not exists public.admin_profile (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text not null,
  email text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.activity_logs (
  id bigint generated by default as identity primary key,
  admin_id uuid not null references auth.users(id) on delete cascade,
  admin_name text not null,
  activity text not null,
  description text not null default '',
  created_at timestamptz not null default now()
);

alter table public.admin_profile enable row level security;
alter table public.activity_logs enable row level security;

-- Hapus kebijakan lama dengan nama yang sama bila skrip dijalankan ulang.
drop policy if exists "admin reads own profile" on public.admin_profile;
drop policy if exists "admin creates own profile" on public.admin_profile;
drop policy if exists "admin reads own activity" on public.activity_logs;
drop policy if exists "admin creates own activity" on public.activity_logs;

create policy "admin reads own profile" on public.admin_profile
  for select to authenticated using (id = auth.uid());
create policy "admin creates own profile" on public.admin_profile
  for insert to authenticated with check (id = auth.uid());
create policy "admin reads own activity" on public.activity_logs
  for select to authenticated using (admin_id = auth.uid());
create policy "admin creates own activity" on public.activity_logs
  for insert to authenticated with check (admin_id = auth.uid());
